version: 0.1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
after_test:
- ps: >-
        $ErrorActionPreference = "Stop"

        dotnet test "tests\JoymonOnline.Orchestration.Tests\JoymonOnline.Orchestration.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=90 /p:ThresholdType=line --configuration Debug --no-build

        if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }

- ps: choco install codecov --no-progress
- ps: codecov.exe -f "tests\JoymonOnline.Orchestration.Tests\coverage.net472.opencover.xml"
artifacts:
- path: '*.nupkg'
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: HMRjdxfeis1x/v3kpdrARcWOCLce/z/YUxqpbchU5w8kanihCO24Yl88QAF1hqkJ
  skip_symbols: true
  on:
    APPVEYOR_REPO_TAG: true
